base_dir: service/app/{port}
storage:
  storage_path: ../../data
  secret_storage: secrets.json
execution:
  execute_in_process: False
  debug: True # enable this if you need more traces
app:
  type: dev
  host: 0.0.0.0
  port: 8080
  debug: True # auto reload app
deployment:
  edition: community
  compute_type: local
