name: Build Doc CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - preview/docs
    paths:
      - 'README.md'
      - 'docs/**'
      - 'scripts/docs/**'
      - '.github/workflows/build_doc_ci.yml'

env:
  packageSetupType: promptflow_with_extra
  testWorkingDirectory: ${{ github.workspace }}/src/promptflow

jobs:
  build_doc_job:
    runs-on: windows-latest
    name: Build Doc
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Python Setup
        uses: "./.github/actions/step_create_python_environment"

      - name: Dev setup
        uses: "./.github/actions/step_sdk_setup"
        with:
          setupType: ${{ env.packageSetupType }}
          scriptPath: ${{ env.testWorkingDirectory }}

      - name: Build doc with reference doc
        shell: powershell
        working-directory: scripts/docs/
        run: |-
          pip install langchain
          ./doc_generation.ps1 -WithReferenceDoc:$true -WarningAsError:$true 

  # Note: We have this job separately because some error may missing when build link check exists.
  link_check_job:
    runs-on: windows-latest
    name: Build Link Check
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build LinkCheck
        shell: powershell
        working-directory: scripts/docs/
        run: ./doc_generation.ps1 -BuildLinkCheck -WarningAsError:$true
