name: tools_tests
on:
  pull_request_target:
    paths:
      - src/promptflow-tools/**
      - '**tools_tests.yml'
  workflow_dispatch:
jobs:
  run_tool_ci_job:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: Tool Test
    timeout-minutes: 30

    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}
      - name: Setup
        # Hotfix promptflow missing dependency issue by pinning to 0.1.0b6
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest_mock
          pip install azure-identity azure-keyvault-secrets
          pip install -r ./src/promptflow-tools/requirements.txt
          pip install promptflow==0.1.0b6
      - name: Generate configs
        run: |
          python ./scripts/tool/generate_connection_config.py --tenant_id ${{ secrets.TENANT_ID }} --client_id ${{ secrets.CLIENT_ID }} --client_secret ${{ secrets.CLIENT_SECRET }}

      - name: Run tests
        run: |
          pytest ./src/promptflow-tools/tests